version: '3'
services:
  vir-db:
    container_name: vir-db
    image: mysql:5.6
    volumes:
      - ./data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    expose:
      - 3306
    environment:
      - MYSQL_ROOT_PASSWORD=test123
      - MYSQL_DATABASE=vir-nut
      - MYSQL_USER=virtual
      - MYSQL_PASSWORD=password